networks:
  OpenVDI_network:
    driver: bridge

# services
services:
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      - OpenVDI_network
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:16.9-alpine
    networks:
      - OpenVDI_network
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole_compose
    group_add:
      - "1000"
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole
    networks:
      - OpenVDI_network
    volumes:
      - ./record:/record:rw
    ports:
    - 8080:8080/tcp
    restart: always

  openvdi:
    build: server/
    container_name: OpenVDI_compose
    command: ["python3", "./main.py"]
    depends_on:
    - guacd
    - postgres
    - guacamole
    env_file:
      - ./server/.env
    networks:
      - OpenVDI_network
    restart: always
